import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "./providers/Provider";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <Provider>
        <ReactQueryProvider>
          <html lang="en">
            <body className={inter.className}>
              <main>{children}</main>
              <Toaster />
            </body>
          </html>
        </ReactQueryProvider>
      </Provider>
    </ClerkProvider>
  );
}
